In [1]:
import numpy as np
import pandas as pd

In [9]:
tipss=pd.read_csv('/Users/eshantharjun/Desktop/ml/data/tipss.csv')
titan=pd.read_csv('/Users/eshantharjun/Desktop/ml/data/titanicdataset.csv')
titan.head()
tipss.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [28]:
tipss['tip_percent']=round((tipss['tip']/tipss['total_bill'])*100,1)
tipss.head()

   total_bill   tip     sex smoker  day    time  size  tip_percent service
0       16.99  1.01  Female     No  Sun  Dinner     2          5.9  normal
1       10.34  1.66    Male     No  Sun  Dinner     3         16.1  normal
2       21.01  3.50    Male     No  Sun  Dinner     3         16.7  normal
3       23.68  3.31    Male     No  Sun  Dinner     2         14.0  normal
4       24.59  3.61  Female     No  Sun  Dinner     4         14.7  normal

In [12]:
print(tipss.iloc[9, 0])
tipss.iloc[-3:, :2]

14.78

     total_bill   tip
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

In [14]:
print(tipss.loc[20:25,'sex':'size'])

       sex smoker  day    time  size
20    Male     No  Sat  Dinner     2
21  Female     No  Sat  Dinner     2
22  Female     No  Sat  Dinner     2
23    Male     No  Sat  Dinner     4
24    Male     No  Sat  Dinner     2
25    Male     No  Sat  Dinner     4

In [24]:
print(tipss[~(tipss['time']=="Dinner")].shape[0])

68

In [26]:
tipss[(tipss['size']>=3) & (tipss['tip']>4)].shape[0]

28

In [37]:
tipss['service']='normal'
tipss.loc[np.where(tipss['tip_percent']>20)[0], 'service'] = 'generous'
tipss.head(20)

    total_bill   tip     sex smoker  day    time  size  tip_percent   service
0        16.99  1.01  Female     No  Sun  Dinner     2          5.9    normal
1        10.34  1.66    Male     No  Sun  Dinner     3         16.1    normal
2        21.01  3.50    Male     No  Sun  Dinner     3         16.7    normal
3        23.68  3.31    Male     No  Sun  Dinner     2         14.0    normal
4        24.59  3.61  Female     No  Sun  Dinner     4         14.7    normal
5        25.29  4.71    Male     No  Sun  Dinner     4         18.6    normal
6         8.77  2.00    Male     No  Sun  Dinner     2         22.8  generous
7        26.88  3.12    Male     No  Sun  Dinner     4         11.6    normal
8        15.04  1.96    Male     No  Sun  Dinner     2         13.0    normal
9        14.78  3.23    Male     No  Sun  Dinner     2         21.9  generous
10       10.27  1.71    Male     No  Sun  Dinner     2         16.7    normal
11       35.26  5.00  Female     No  Sun  Dinner     4         14.2    normal
12       15.42  1.57    Male     No  Sun  Dinner     2         10.2    normal
13       18.43  3.00    Male     No  Sun  Dinner     4         16.3    normal
14       14.83  3.02  Female     No  Sun  Dinner     2         20.4  generous
15       21.58  3.92    Male     No  Sun  Dinner     2         18.2    normal
16       10.33  1.67  Female     No  Sun  Dinner     3         16.2    normal
17       16.29  3.71    Male     No  Sun  Dinner     3         22.8  generous
18       16.97  3.50  Female     No  Sun  Dinner     3         20.6  generous
19       20.65  3.35    Male     No  Sat  Dinner     3         16.2    normal

In [ ]:
titan['Embarked'].value_counts()

np.int64(889)

In [41]:
# B2

# 1. Women in third class
print(((titan['Sex'] == 'female') & (titan['Pclass'] == 3)).sum())

# 2. Women in third class who survived
print(((titan['Sex'] == 'female') & (titan['Pclass'] == 3) & (titan['Survived'] == 1)).sum())

144
72

In [42]:
# B3

print(titan.loc[titan['Fare'] > 200, ['Name', 'Age', 'Fare']])

print("Number of passengers:", (titan['Fare'] > 200).sum())

                                                  Name   Age      Fare
27                      Fortune, Mr. Charles Alexander  19.0  263.0000
88                          Fortune, Miss. Mabel Helen  23.0  263.0000
118                           Baxter, Mr. Quigg Edmond  24.0  247.5208
258                                   Ward, Miss. Anna  35.0  512.3292
299    Baxter, Mrs. James (Helene DeLaudeniere Chaput)  50.0  247.5208
311                         Ryerson, Miss. Emily Borie  18.0  262.3750
341                     Fortune, Miss. Alice Elizabeth  24.0  263.0000
377                          Widener, Mr. Harry Elkins  27.0  211.5000
380                              Bidois, Miss. Rosalie  42.0  227.5250
438                                  Fortune, Mr. Mark  64.0  263.0000
527                                 Farthing, Mr. John   NaN  221.7792
557                                Robbins, Mr. Victor   NaN  227.5250
679                 Cardeza, Mr. Thomas Drake Martinez  36.0  512.3292
689                  Madill, Miss. Georgette Alexandra  15.0  211.3375
700  Astor, Mrs. John Jacob (Madeleine Talmadge Force)  18.0  227.5250
716                      Endres, Miss. Caroline Louise  38.0  227.5250
730                      Allen, Miss. Elisabeth Walton  29.0  211.3375
737                             Lesurer, Mr. Gustave J  35.0  512.3292
742              Ryerson, Miss. Susan Parker "Suzette"  21.0  262.3750
779  Robert, Mrs. Edward Scott (Elisabeth Walton Mc...  43.0  211.3375
Number of passengers: 20

In [43]:
# B4

first = titan[titan['Pclass'] == 1]
third = titan[titan['Pclass'] == 3]

first_survival = (first['Survived'] == 1).mean() * 100
third_survival = (third['Survived'] == 1).mean() * 100

print(first_survival)
print(third_survival)

# First class: 62.96%, Third class: 24.24%

62.96296296296296
24.236252545824847

In [44]:
# B5

titan['age_group'] = 'adult'
titan.loc[titan['Age'] < 18, 'age_group'] = 'child'

print(titan['age_group'].value_counts())

age_group
adult    778
child    113
Name: count, dtype: int64